on:
  pull_request:
    branches:
      - main
jobs:
  bytebase-review-sql:
    runs-on: ubuntu-latest
    env:
      BYTEBASE_URL: "https://56c6-103-170-72-209.ngrok-free.app"
      BYTEBASE_PROJECT: "projects/project-sample"
      BYTEBASE_SERVICE_ACCOUNT: "ci@service.bytebase.com"
      BYTEBASE_TARGETS: "instances/prod-sample-instance/databases/db1,instances/prod-sample-instance/databases/db2"
      FILE_PATTERN: "db/migration_sql/*.sql"
    name: Review SQL
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/login-action@main
        with:
          bytebase-url: ${{ env.BYTEBASE_URL }}
          service-key: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-secret: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: sql review
        id: sql_review
        uses: bytebase/create-release-action@v1
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          project: ${{ env.BYTEBASE_PROJECT }}
          file-pattern: ${{ env.FILE_PATTERN }}
          # fail the action if release checks report any error.
          check-release: "FAIL_ON_ERROR"
          targets: ${{ env.BYTEBASE_TARGETS }}
          validate-only: true
